name: workflow overview

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  my_self_hosted_job:
    name: my self hosted job
    runs-on: self-hosted
    steps:
      - name: step in a self-hosted runner
        id: selfhostedID
        shell: sh
        run: |
          echo |
            echo this is a multiline comment
            echo and this job has been executed from my self-hosted runner
  a_simple_job:
    name: my simple job
    runs-on: ubuntu-latest
    steps:
      - name: name of my step
        id: stepID
        run: echo "this is the first step from the first job"
      - name: step with another job
        id: shellStep
        shell: python
        run: print("this is using the python shell")
      - name: toJSON function
        run: |
          echo |
           echo "${{toJson(runner)}}"
           echo "${{toJson(job)}}"
           echo "${{toJson(steps)}}"
